import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>      
        <div className="min-h-screen relative bg-gray-50 dark:bg-gray-900 flex items-center justify-center px-16">
          {/* Animated Cash Green Blobs */}
          <div className="absolute bottom-[45%] left-[40%] size-180 bg-lime-300 dark:bg-lime-400 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
          <div className="absolute top-[35%] right-[30%] size-180 bg-green-300 dark:bg-lime-400 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
          <div className="relative mx-auto w-full max-w-sm sm:max-w-md md:max-w-lg lg:max-w-3xl px-0 lg:px-6 min-h-screen">
            {/* Status Bar */}
            <div className="flex justify-between items-center px-6 py-3 text-sm font-medium">
              <span>9:41</span>
              <div className="flex items-center gap-1">
                <div className="flex gap-1">
                  <div className="w-1 h-3 bg-foreground rounded-full" />
                  <div className="w-1 h-3 bg-foreground rounded-full" />
                  <div className="w-1 h-3 bg-foreground rounded-full" />
                  <div className="w-1 h-3 bg-muted-foreground/50 rounded-full" />
                </div>
                <svg className="w-4 h-4 ml-1" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M2 17h20v2H2zm1.15-4.05L4 11.47l.85 1.48L3.5 14.4l-.35-.95zm2.8-2.8L5.47 12 6.95 10.15l1.48.85-.95.35zm5.05.9L12.47 8 14.4 9.5l-.95.35-.85-1.48zm2.8 2.8L12.15 12l1.48 1.85-.85 1.48-.35-.95zm-2.8 2.8L9.53 16l-1.48-1.85.85-1.48.35.95zm-2.8-2.8L8.85 12 7.37 13.85l-1.48-.85.95-.35z" />
                </svg>
                <div className="w-6 h-3 border border-foreground rounded-sm">
                  <div className="w-4 h-1.5 bg-foreground rounded-sm m-0.5" />
                </div>
              </div>
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
